name: GitHub Actions CI
run-name: ${{ github.actor }} is pushing code 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run ci:lint

      - name: Build project
        run: npm run ci:build

      - name: Run tests
        run: npm run ci:test
